name: tags-similarity
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<2.0
  - scikit-learn
  - pip
  - pip:
      - flask>=3.0.0,<4.0.0
      - spacy>=3.6.0,<4.0.0
      - sentence-transformers>=2.5.0,<3.0.0
      - werkzeug>=2.3.0,<3.0.0
      - typing-extensions>=4.5.0
      - gunicorn>=20.1.0,<22.0.0
      - thinc>=8.0.0,<9.0.0
