services:
  # Web service configuration
  - type: web
    name: tags-similarity-calculation
    runtime: python
    repo: https://github.com/Mohammed87FS/Tags_Similarity_Calcualtion.git
    branch: render
    rootDir: .
    buildCommand: poetry install && python -m spacy download en_core_web_sm && chmod +x render_startup.sh
    startCommand: ./render_startup.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: DATA_DIR
        value: /opt/render/project/src/python/data
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: GUNICORN_WORKERS
        value: "2"
